### ISSUE TITLE
Issues with tx_lines()

### ISSUE THREAD

**Issue by devonboyne** [oncology-outcomes/o2r#4]
Some items to address:

1) The ordering of the agents within a regimen seems to be dependent on the chronological order in which the agents were received. Need to revise so they appear in alphabetical order in the regimen name such that there are not multiple permutations for the same regimen with different agent orderings (e.g. "Drug A + B + C", "Drug B + A + C", "Drug C + B + A", etc.). 

2) Implement check to ensure dependencies are up to date and insert error message if not

3) `multiple = "error"` was deprecated in dplyr 1.1.1. Please use `relationship = "many-to-one"` instead.

4) Potential issue with capturing new lines of therapy that have agents given in previous lines.

**Comment by mattwarkentin** [comment]
Fixed (hopefully) with ee79be18193bac23fd0b8e5fce7ef162a71271ef
